apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-app-manager
  template:
    metadata:
      labels:
        app: scale-app-manager
    spec:
      serviceAccountName: ksa-scale-cluster
      containers:
        - name: scale-manager
          image: app_manager
          imagePullPolicy: IfNotPresent
          command:
          - npm
          - run
          - start:manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-app-worker
  template:
    metadata:
      labels:
        app: scale-app-worker
    spec:
      containers:
        - name: scale-worker
          image: app_worker:new
          imagePullPolicy: IfNotPresent
          command:
          - npm
          - run
          - start:worker
# ---
# apiVersion: policy/v1beta1
# kind: PodDisruptionBudget
# metadata:
#   labels:
#     app: mass-push-v3-worker
#   name: mass-push-v3-worker
# spec:
#   maxUnavailable: 1
#   selector:
#     matchLabels:
#       app: mass-push-v3-worker
