apiVersion: v1
kind: Pod
metadata:
  name: sample-lifecycle
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      command: ["sh", "-c", "touch /tmp/started; sleep 360"]
      lifecycle:
        postStart: # コンテナ起動後にコマンドを実行
          exec:
            command: ["/bin/sh", "-c", "sleep 20; touch /tmp/poststart"]
        preStop: # コンテナ停止直前にコマンドを実行
          exec:
            command: ["/bin/sh", "-c", "touch /tmp/prestop; sleep 20"]
