apiVersion: v1
data:
  KEY1: VAL1
  sample.txt: hello world!!!!
kind: ConfigMap
metadata:
  name: generated-configmap-8g4km2mhb7
---
apiVersion: v1
kind: Service
metadata:
  name: sample-lb
spec:
  ports:
  - name: http-port
    nodePort: 30082
    port: 8080
    protocl: TCP
    targetPort: 80
  selector:
    app: sample-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchlabels:
      app: sample-app
    template:
      metadata:
        labels:
          app: sample-app
      spec:
        containers:
        - image: nginx:1.16
          name: nginx-container
