apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sample-external-secret
spec:
  backendType: gcpSecretManager
  # GCPのプロジェクトID
  projectId: _PROJECT_
  data:
  - key: sample-gsm-key
    name: sample-k8s-key
    version: latest
