apiVersion: v1
kind: Service
metadata:
  name: sample-ingress-svc-2
spec:
  type: NodePort
  ports:
  - name: 'http-port'
    protocol: 'TCP'
    port: 8888
    targetPort: 80
  selector:
    ingress-app: sample2
