version: '3.7'

x-service-default: &service
  build:
    context: ./
    dockerfile: ./docker/Dockerfile
  working_dir: /usr/src/app

services:
  worker:
    <<: *service
    command: npm run start:worker

  manager:
    <<: *service
    command: npm run start:manager
