apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-wordpress
  name: sample-ingress-default
spec:
  ports:
  - name: http-port
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-wordpress
    ingress-app: default
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-wordpress
  name: sample-ingress-svc-1
spec:
  ports:
  - name: http-port
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-wordpress
    ingress-app: sample1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-wordpress
  name: sample-ingress-svc-2
spec:
  ports:
  - name: http-port
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-wordpress
    ingress-app: sample2
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-wordpress
    ingress-app: sample1
  name: sample-ingress-app-1
spec:
  containers:
  - image: amsy810/echo-nginx:v2.0
    name: nginx-container
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-wordpress
    ingress-app: sample2
  name: sample-ingress-app-2
spec:
  containers:
  - image: amsy810/echo-nginx:v2.0
    name: nginx-container
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-wordpress
    ingress-app: default
  name: sample-ingress-default
spec:
  containers:
  - image: amsy810/echo-nginx:v2.0
    name: nginx-container
