apiVersion: v1
kind: Service
metadata:
  annotations:
    annotation1: annotaiton-val1
  labels:
    label1: label1-val
  name: sample-lb
spec:
  ports:
  - name: http-port
    nodePort: 30082
    port: 8080
    protocl: TCP
    targetPort: 80
  selector:
    app: sample-app
    label1: label1-val
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    annotation1: annotaiton-val1
  labels:
    label1: label1-val
  name: sample-deployment
spce:
  replicas: 3
  selector:
    matchlabels:
      app: sample-app
    template:
      metadata:
        labels:
          app: sample-app
      spec:
        containers:
        - image: nginx:1.16
          name: nginx-container
spec:
  selector:
    matchLabels:
      label1: label1-val
  template:
    metadata:
      annotations:
        annotation1: annotaiton-val1
      labels:
        label1: label1-val
