apiVersion: v1
kind: Pod
metadata:
  name: sample-restart-onfailure
spec:
  restartPolicy: OnFailure # Podで実行しているコマンドが実行した場合に、再起動する
  containers:
    - name:  nginx-contianer
      image: nginx:1.12
      # command: ["sh", "-c", "exit 0"]
      command: ["sh", "-c", "exit 1"]