apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scale-cluster-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scale-clusterrole
subjects:
- kind: ServiceAccount
  name: ksa-scale-cluster
  namespace: default
