apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-cluster-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-role
subjects:
- kind: ServiceAccount
  name: ksa-scale-cluster
  namespace: default