apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-role
  namespace: default
rules:
  - apiGroups:
    - apps
    - extensions
    resources:
    - replicasets
    - deployments
    - deployments/scale
    verbs:
    - "*"
