apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spce:
  replicas: 3
  selector:
    matchlabels:
      app: sample-app
    template:
      metadata:
        labels:
          app: sample-app
      spec:
        containers:
        - name: nginx-container
          image: nginx:1.16

